import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  calculateShannonEntropy,
  looksAutoGenerated,
  analyzeUsernamePatterns,
} from "../chrome-extension/modules/username-patterns.js";

describe("calculateShannonEntropy", () => {
  it("returns 0 for empty string", () => {
    assert.equal(calculateShannonEntropy(""), 0);
  });

  it("returns 0 for null", () => {
    assert.equal(calculateShannonEntropy(null), 0);
  });

  it("returns 0 for single repeated char", () => {
    assert.equal(calculateShannonEntropy("aaaa"), 0);
  });

  it("returns 1 for two equally distributed chars", () => {
    const e = calculateShannonEntropy("ab");
    assert.ok(Math.abs(e - 1.0) < 0.001);
  });

  it("increases with more unique characters", () => {
    const e2 = calculateShannonEntropy("ab");
    const e4 = calculateShannonEntropy("abcd");
    assert.ok(e4 > e2);
  });
});

describe("looksAutoGenerated", () => {
  it("detects sequential number suffix (user12345)", () => {
    assert.equal(looksAutoGenerated("user12345"), true);
    assert.equal(looksAutoGenerated("dev98765"), true);
  });

  it("detects consonant clusters", () => {
    assert.equal(looksAutoGenerated("xfghtjk"), true);
  });

  it("detects alternating letter-number", () => {
    assert.equal(looksAutoGenerated("a1b2c3d4"), true);
  });

  it("detects hex-heavy usernames", () => {
    assert.equal(looksAutoGenerated("a3f2e8b1c9"), true);
  });

  it("detects prefix + UUID pattern", () => {
    assert.equal(looksAutoGenerated("user-a3f2e8b1c9"), true);
  });

  it("allows normal human usernames", () => {
    assert.equal(looksAutoGenerated("john"), false);
    assert.equal(looksAutoGenerated("alice-dev"), false);
    assert.equal(looksAutoGenerated("bob42"), false);
  });

  it("allows short common usernames", () => {
    assert.equal(looksAutoGenerated("mike"), false);
    assert.equal(looksAutoGenerated("sara"), false);
  });
});

describe("analyzeUsernamePatterns", () => {
  it("returns neutral for insufficient profiles", () => {
    const result = analyzeUsernamePatterns([{ login: "a" }, { login: "b" }]);
    assert.equal(result.subscore, 0.5);
  });

  it("scores high for normal usernames", () => {
    const profiles = [
      { login: "alice" },
      { login: "bob" },
      { login: "charlie" },
      { login: "diana" },
      { login: "edward" },
      { login: "fiona" },
    ];
    const result = analyzeUsernamePatterns(profiles);
    assert.ok(result.subscore >= 0.9);
    assert.equal(result.signals[0].severity, "ok");
  });

  it("flags high percentage of auto-generated names", () => {
    const profiles = [
      { login: "user12345" },
      { login: "dev98765" },
      { login: "user54321" },
      { login: "dev11111" },
      { login: "user99999" },
      { login: "alice" },
    ];
    const result = analyzeUsernamePatterns(profiles);
    assert.ok(result.subscore < 0.6);
    assert.ok(result.suspiciousPercent > 40);
  });
});
